COMMON: &common
  DEBUG: False
  TESTING: False

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SOURCE:
    PG:
      DBNAME: postgres
      HOST: localhost
      USER: postgres
      PASSWORD: postgres
PRODUCTION: &production
  <<: *common

TESTING: &testing
  <<: *common
  TESTING: True
